server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

metrics:
  export:
    prometheus:
      enabled: true

management:
  tracing:
    enabled: true
    sampling:
      probability: 0.5
  zipkin:
    tracing:
      endpoint: http://team6-zipkin:9411/api/v2/spans
